name: managemen_keuangan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  calendar_appbar: ^0.0.6
  intl: ^0.17.0
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  # Firebase dependencies
  firebase_core: "^1.10.0"
  firebase_auth: "^3.3.3"
  cloud_firestore: "^3.1.7"

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  video_player: ^2.2.16

flutter:
  uses-material-design: true
  assets:
    - assets/images/dribble1.jpeg
    - assets/images/agility1.jpeg
    - assets/images/defense1.jpeg
    - assets/images/finishing1.jpeg
    - assets/images/passing1.jpeg
    - assets/images/shooting1.jpeg
    - assets/video/crossover.mp4
    - assets/video/stationary.mp4
    - assets/images/terbaru0.jpeg
    - assets/video/blind.mp4
    - assets/images/terbaru1.jpeg
    - assets/images/terbaru2.jpeg
    - assets/images/terbaru3.jpeg
    - assets/images/terbaru4.jpeg